const areas = [
  "Vadiparti",
  "Suthar Vas",
  "Mandir Vas",
  "Undo Vas",
  "Kajivdo Parti Vas",
  "Barot Vas",
  "Tichudiyu",
  "Brahman Vas",
  "Panchal Vas",
  "Nayak Vas",
  "Rabari Vas",
  "Nayee Vas",
  "Vaniya Vas",
  "Kabir Vas",
  "Juno Raval Vas",
  "Prajapati Vas",
  "Dantani Vas",
  "Navo Raval Vas",
  "Bajaniya Vas",
  "Vrundavan Society",
  "Darbar Vas",
  "Jethi Paru",
  "Thalor Vas Paru",
  "Gojariya Parti",
  "Moto Thakor Vas",
  "Vankar Vas",
  "Indira Nagar Vasahat",
  "Laxminarayan Society",
  "Sitabag Society",
  "Purushottam Nagar Society",
  "Ambika Nagar Society",
  "Gulab Nagar",
  "Bheel Vas (Ravatjino Tekro)",
];

const iconsList = {
  Robbery: "robber",
  Fire: "fire",
  Police: "police-badge",
  Accident: "car",
  SOS: "alert-circle",
};

export default {
  area: areas,
  emerIconList: iconsList,
};
